package com.interview.array;
/*
 * https://leetcode.com/problems/find-the-difference/
 * 
 * Category: Easy, xor
 * 
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 */

public class FindtheDifference {
    public char findTheDifference(String s, String t) {
        int len1 = s.length();
        int len2 = t.length();
        int smallLength = len1 < len2 ?  len1 : len2;
        

        int index = 0;
        for (int i = 0; i < smallLength; i++) {
            index^= s.charAt(i) - 'a';
            index^= t.charAt(i) - 'a';
        }
        
        //See last one
        if (len1 > len2) {
            index^= s.charAt(len1-1) - 'a';
        } else {
            index^= t.charAt(len2-1) - 'a';
        }
        return (char)('a' + index);
         
    }
}
